### ISSUE TITLE
Use EIP-6963 to reliably detect MetaMask

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-directory#280]
If a user has MetaMask running alongside other extensions that imitate MetaMask, the directory site will have trouble detecting that MetaMask is already installed

In order to reliably detect MetaMask, the site could use EIP-6963. Example here: https://github.com/Montoya/snap-connect-example

For now, it could treat all instances of MetaMask the same (stable, Flask, MMI). In the future we can explore treating them differently.

**Comment by ritave** [comment]
Cross comment from https://github.com/MetaMask/template-snap-monorepo/issues/128#issuecomment-1908885186

Async nature of EIP-6963 disallows detection of below scenarios:

No wallet installed
No installed wallet supports Snaps
This is because there's no way to know how long a DApp should wait for eip6963:announceProvider event.

My suggestion is to continue using window.ethereum.detected and window.ethereum.providers which will finish in a known finite amount of time.
